# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_ROOT_PASSWORD: password 
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 5432 on the container
      - '5432'
      # Where our data will be persisted
    volumes:
      - ./data:/var/lib/mysql

# Names our volume
volumes:
  my-db:
